# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import musicstats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('thumbnail', models.ImageField(upload_to=musicstats.models.artist_thumbnail_path)),
                ('image', models.ImageField(upload_to=musicstats.models.artist_image_path)),
                ('musicbrainz_id', models.CharField(max_length=255)),
                ('wiki_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_artist', models.TextField()),
                ('title', models.TextField()),
                ('thumbnail', models.ImageField(upload_to=musicstats.models.song_thumbnail_path)),
                ('image', models.ImageField(upload_to=musicstats.models.song_image_path)),
                ('musicbrainz_id', models.CharField(max_length=255)),
                ('wiki_content', models.TextField()),
                ('itunes_url', models.TextField()),
                ('amazon_url', models.TextField()),
                ('artists', models.ManyToManyField(to='musicstats.Artist')),
            ],
        ),
    ]
