# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import musicstats.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicstats.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('logo', models.ImageField(upload_to=musicstats.models.logo_image_path)),
                ('thumbnail', models.ImageField(upload_to=musicstats.models.logo_thumbnail_path)),
                ('slogan', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='songplay',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicstats.Station'),
        ),
    ]
