# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicstats', '0002_auto_20170417_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicstats.Song')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicstats.Station')),
            ],
        ),
    ]
