# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstats', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[(b'B', b'Burned'), (b'U', b'Upvote'), (b'D', b'Downvote')], default=b'U', max_length=1),
        ),
    ]
