# Generated by Django 2.2.4 on 2019-09-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicstats", "0005_epgentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="epgdatasource",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
