# Generated by Django 2.2.4 on 2019-09-21 08:00

from django.db import migrations, models
import musicstats.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstats', '0006_auto_20190921_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='logo_square',
            field=models.ImageField(blank=True, upload_to=musicstats.models.logo_square_path),
        ),
    ]
