# Generated by Django 3.0.8 on 2020-07-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musicstats", "0010_remove_epgentry_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epgdatasource",
            name="granularity_mins",
        ),
    ]
