# Generated by Django 3.0.8 on 2020-07-28 12:55

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("musicstats", "0011_remove_epgdatasource_granularity_mins"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="Europe/London"),
        ),
    ]
